feat: add support for reserved instances #148
cloudposse/terraform-aws-rds pull request #190
Opened 2024-09-12 13:48 UTC by kevcube

2024-09-12 15:21 UTC, kevcube commented
/terratest

2024-09-12 21:13 UTC, Gowiem requested changes
@kevcube one best practice to follow. Also, regarding your comment: 

> bats is failing because not all outputs have descriptions but I am not seeing any outputs without descriptions.

[See lines here in `examples/complete`](https://github.com/cloudposse/terraform-aws-rds/blob/main/examples/complete/outputs.tf#L41-L51). Fix those and request me as a reviewer and I'll give it another once through.

2024-09-12 21:13 UTC, Gowiem commented on variables.tf
> +variable "use_reserved_instances" {
Cloud posse convention (and ours too!): Use `_enabled` for `bool` type variables. [See here](https://docs.cloudposse.com/best-practices/terraform/#use-positive-variable-names-to-avoid-double-negatives).

2024-09-13 14:49 UTC, Gowiem commented
@kevcube see my review comment for how to fix bats tests

2024-09-16 13:13 UTC, kevcube commented
@Gowiem I see no review comment 👀

2024-09-16 13:23 UTC, Gowiem commented
![image](https://github.com/user-attachments/assets/4313c5af-7f46-4562-be82-a5b677eb6323)

@kevcube

2024-09-16 13:26 UTC, kevcube commented
oh duh. ok thanks, fixed.

2024-09-16 13:26 UTC, kevcube commented
/terrateset

2024-09-16 13:26 UTC, kevcube commented
/terratest

2024-09-16 13:29 UTC, kevcube commented
/terratest

2024-10-12 13:49 UTC, closed without merging