Upgrade dependency modules for support tf14
cloudposse/terraform-aws-rds pull request #80
Opened 2020-12-15 16:32 UTC by guyelia

## what
* Upgrading dependency modules to versions that supporting Terraform 14

## why
* For using this module with Terraform 14

2020-12-15 19:07 UTC, joe-niland requested changes

2020-12-15 20:15 UTC, guyelia commented
@joe-niland thanks! upgraded to v13 format.

2020-12-15 20:31 UTC, joe-niland commented
/test all

2020-12-15 20:31 UTC, joe-niland commented
@guyelia thank you - let's see how the tests go

2020-12-15 20:56 UTC, joe-niland commented
/rebuild-readme

2020-12-15 21:48 UTC, joe-niland commented
The tests need updating to be compatible with the automation.

Did you want to have a go with the following?

```
 make init
 make github/init
 cd test/src/
 go mod init github.com/cloudposse/$(cd ../../ && basename `pwd`)
 go mod tidy
 git rm Gopkg.*
 git add go.*
 cp ../../../terraform-null-label/test/src/Makefile 
```

2020-12-15 22:00 UTC, guyelia commented
/test all

2020-12-15 22:02 UTC, guyelia commented
/rebuild-readme

2020-12-15 22:12 UTC, guyelia commented
/test all

2020-12-15 22:16 UTC, joe-niland commented
/rebuild-readme

2020-12-15 22:33 UTC, joe-niland commented
/test all

2020-12-15 22:53 UTC, joe-niland commented on context.tf
> +#
Variables that conflict with this file need to be removed from variables.tf

2020-12-16 10:47 UTC, guyelia commented
/test all

2020-12-16 11:05 UTC, guyelia commented
/test all

2020-12-16 12:44 UTC, guyelia commented
/test all

2020-12-16 12:50 UTC, guyelia commented
/rebuild-readme

2020-12-16 12:55 UTC, guyelia commented
I gave up :(

2020-12-16 21:48 UTC, joe-niland commented
/test all

2020-12-16 21:48 UTC, joe-niland commented
@guyelia some commands are restricted

2020-12-17 10:10 UTC, closed without merging